### ISSUE TITLE
CLI: merge Send and SendMicro?

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#150]
What's the point of having both ?

**Comment by Thoralf-M** [comment]
Edit: Just noticed that this is for the CLI, comment below is about the functions in the wallet

One argument for keeping them separated is that no outputs can have a SDRUC and expiration added which can lock up the storage deposit without knowing it before
But since it expires after 1 day by default if not claimed, it should be fine to merge them

What I'm asking myself more is if we should maybe even remove both and only use `prepare_output()` instead
