### ISSUE TITLE
[Bug]: Expiration unlock condition not working when using sendWithParams (nodejs bindings)

### ISSUE THREAD

**Issue by tangleMesh** [iotaledger/iota-sdk#1529]
### Issue description

We send SMR & IOTA amounts to external wallets using the `sendWithParams` and set the `expiration` porperty to 30 days as we'd like to prevent lost funds when using an invalid or unused address.

We call the function like this:
```
const sendMessage = await this.account.sendWithParams (
                [{
                    address: _address,
                    amount: BigInt (convertUnits (_amount, "M", "")),
                    expiration: 60 * 60 * 24 * 30, // 30 days expiration
                }],
                {
                    taggedDataPayload: undefined,
                    allowMicroAmount: true,
                    note: _message,
                }
            );
```

We'd expect, that the amount is being sent and the receiver needs to claim these funds. But when looking at the transaction we can't claim it with firefly and even in the explorer there is no expiration visible.

Do we use the method in a wrong way, or is there some other issue here?

Thank you very much for your help!

### Version

We use the nodejs bindings in version `v1.1.0`.

### Expected behaviour

The transactions are sent with an expiration flag and when the receiver does not claim the tokens within 30 days we'd get them refunded to our sender account.

### Actual behaviour

The transaction is sent to the receiver address but it's not required to claim the amount and if a wrong address is used, the funds are lost.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [x] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
https://wiki.iota.org/iota-sdk/references/nodejs/interfaces/SendParams/#expiration
> The expiration will only be used if one is necessary given the provided amount

This means it will only be added if the amount you try to send is below the minimum required storage deposit, because otherwise there is no need for a storage deposit return and expiration unlock condition

You can still send outputs with an expiration unlock condition by building them with https://wiki.iota.org/iota-sdk/references/nodejs/classes/Client/#buildbasicoutput or https://wiki.iota.org/iota-sdk/references/nodejs/classes/Account/#prepareoutput and then send with https://wiki.iota.org/iota-sdk/references/nodejs/classes/Account/#sendoutputs

**Comment by tangleMesh** [comment]
Ah okay, the i've got a misconception on how the expiration flag is meant to be used. Thank you!
