### ISSUE TITLE
Remaining TransactionFailureReason questions

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1954]
Questions for Philipp
- [x] `Self::DelegationStartEpochInvalid => write!(f, "invalid start epoch."),` should this mention delegation? Staking also has a start epoch field
- [x] Should `ChainOutputImmutableFeaturesChanged` be used for other immutable fields that are not features? Like a Foundry's serial number, maximum supply, ... for example.
- [x] Which error is used if an Anchor modifies fields with the wrong transition type?
- [x] Which error is used if Anchor state index is decreasing?
- [x] Is `TypeInvalid` about the signed transaction payload type?
- [x] What exactly is `Conflicting`?
- [x] `CommitmentInputMissing` should be syntactic?
- [x] `NativeTokenAmountLessThanZero` and `NativeTokenSumExceedsUint256` could be combined like `ManaOverflow`? Or what is it describing?
- [x] Which error is used if the account ID of an account transitioned from an implicit account is null?
- [x] Which error is used if an account transitioned from an implicit account is not a block issuer?
- [x] What error should be used if minted tokens or melted tokens decrease in a transition?
- [x] What error should be used for NativeToken count > 64?

Remaining tasks
- [x] Handle `InputCreationAfterTxCreation`

**Comment by PhilippGackstatter** [comment]
> Which error is used if an Anchor modifies fields with the wrong transition type?

The now introduced `TxFailureAnchorInvalidStateTransition` and `TxFailureAnchorInvalidGovernanceTransition` respectively.

>  Which error is used if Anchor state index is decreasing?

`TxFailureAnchorInvalidStateTransition`

>  Is `TypeInvalid` about the signed transaction payload type?

It's currently returned for both invalid `SignedTransaction` or `Transaction` payload types. It's used in iota-core when we cannot downcast an interface to the expected type. Although I now think that this is much more akin to an internal error than something that we need to have in the TX Failure Reasons, since an incorrect payload type would never get past the syntactic check. So I'll remove `TxFailureTypeInvalid`.

>  What exactly is `Conflicting`?

It means that some TX A was conflicting with one or more other transactions and that A was the one that was rejected.

> `CommitmentInputMissing` should be syntactic?

True, I removed it from the mapping.

>  `NativeTokenAmountLessThanZero` and `NativeTokenSumExceedsUint256` could be combined like `ManaOverflow`? Or what is it describing?

- Removed `NativeTokenAmountLessThanEqualZero`. It's only returned from syntactic checks (when native token value is 0 or when the sign of the `big.Int` is negative, which should not even be possible to occur since the serialization is `uint256`). I think it was there before and I didn't check if it was actually returned in the VM.
- Also removed `NativeTokenSumExceedsUint256` since it is also only returned from syntactic checks.

>  Which error is used if the account ID of an account transitioned from an implicit account is null?

That would be `ImplicitAccountDestructionDisallowed` since the VM would detect that as "implicit account on the input side with no corresponding account output on the output side".

>  Which error is used if an account transitioned from an implicit account is not a block issuer?

That would be `BlockIssuerNotExpired` since the implicit account's _implicit_ Block Issuer Feature has an `Expiry Slot` set to `u32::MAX` ([TIP-42](https://github.com/iotaledger/tips/blob/tip42/tips/TIP-0042/tip-0042.md#conversion-semantic-transaction-validation-rules)) and therefore removing it in _current slot_ would be an attempt to remove an unexpired block issuer feature.

>  Should `ChainOutputImmutableFeaturesChanged` be used for other immutable fields that are not features? Like a Foundry's serial number, maximum supply, ... for example.

I imagine debugging a `ImmutableFeaturesChanged` error is still easier than `ImmutableFieldChanged` since the latter could refer to a lot more error cases. So I would personally stick with the current approach if you're fine with it.

>  What error should be used if minted tokens or melted tokens decrease in a transition?

Thanks for bringing that up. I missed that part during the refactoring. I now did that and introduced `ErrSimpleTokenSchemeMintedMeltedTokenDecrease` for the case you're referring to.

>  What error should be used for NativeToken count > 64?

We only allow one Native Token in each Native Token Feature, so I'm not sure what you're referring to.

>  Would it be possible to have an amount overflow error like the mana one? Could happen with private tangle configurations.

I don't see how that could happen thanks to this syntactic rule in TIP-45:
> The sum of all `Amount` fields must not exceed `Token Supply`.

>  What error should be used on invalid unlock method? Like a Signature for an AccountAddress?

For example, when unlocking a chain output with a signature unlock you can use `ErrInvalidChainAddressUnlock`. When unlocking a direct unlockable address (like an `Ed25519 Address` or `Implicit Account Creation Address`) then you can use `ErrInvalidDirectUnlockableAddressUnlock`.

>  What error should be used if an NFT/Account/Anchor unlock point to a different but same type NFT/Account/Anchor?

"different but same" Not sure I understand what you mean exactly.
But the errors for mismatched unlocks are the ones from the question above. The [error message itself](https://github.com/iotaledger/iota.go/blob/fb02a26fc8ebcdcce6fd60ab8d3527c17b8dafac/vm/vm.go#L456) would specify the concrete mismatched errors but creating dedicated errors for each possible combination is too much, imho.

>  `Self::DelegationStartEpochInvalid => write!(f, "invalid start epoch."),` should this mention delegation? Staking also has a start epoch field

I expanded it to `delegation output has invalid start epoch`, but in our case it would end up as a "joined" error from `ErrDelegationTransitionInvalid` and `ErrDelegationStartEpochInvalid` which would be printed as `invalid delegation output transition: [delegation output has] invalid start epoch` which would already have the necessary context to make it clear that it's about delegation outputs.

Changes are here: https://github.com/iotaledger/iota.go/pull/685.

Thanks for raising those issues!

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/1997
