### ISSUE TITLE
Use commitment input slot or tx creation slot for delegation rewards?

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-sdk#1995]
https://github.com/iotaledger/iota-sdk/pull/1961#discussion_r1487367012

**Comment by PhilippGackstatter** [comment]
Hello, just happend to see this question. If `get_output_mana_rewards` calls the `rewards` API to calculate delegation rewards, then that calculation need to use the Commitment Index from the Commitment Input. Generally, (almost) anything time-related needs to use a Commitment Input. The only exception are Potential Mana (generation + decay) and Stored Mana (decay) calculations, which always use the Transaction Creation Slot. 

The reason why we didn't just always use a Commitment Input is to better support offline signing. For instance, when you have a simple Basic Output and you just want to transfer it, then requiring a Commitment Input for the Potential Mana calculation would make offline signing much harder, since the oldest commitment that can be picked is `Max Committable Age` old, while the TX Creation Slot can be chosen much more freely in comparsion and you could just wrap that TX in a block a day later and be fine.

**Comment by Thoralf-M** [comment]
Thanks for the explanation!

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota-sdk/pull/2056
