### ISSUE TITLE
[Bug]: Can't parse output, but explorer can

### ISSUE THREAD

**Issue by abcen7** [iotaledger/iota-sdk#2252]
### Issue description

{'type': 'client', 'error': 'node error: The requested data https://api.stardust-mainnet.iotaledger.net/api/core/v2/outputs/0x1e24c1fb2841657fb623800a694e57db5478f4b57810fe1bd1f423a593f1283c0100 was not found.'}

There is all good: https://explorer.iota.org/mainnet/output/0x1e24c1fb2841657fb623800a694e57db5478f4b57810fe1bd1f423a593f1283c0100

### Version

iota-sdk==1.1.4

### Expected behaviour

A parsed output

### Actual behaviour

{'type': 'client', 'error': 'node error: The requested data https://api.stardust-mainnet.iotaledger.net/api/core/v2/outputs/0x1e24c1fb2841657fb623800a694e57db5478f4b57810fe1bd1f423a593f1283c0100 was not found.'}

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

`output = client.get_output(output_id)`

### Errors

{'type': 'client', 'error': 'node error: The requested data https://api.stardust-mainnet.iotaledger.net/api/core/v2/outputs/0x1e24c1fb2841657fb623800a694e57db5478f4b57810fe1bd1f423a593f1283c0100 was not found.'}

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Hello, this is not a bug. The reason for this is that our nodes prune the history after ~2 weeks (if you run your own node you can specify in the config how long it should keep it) and this output was already spent 2023-12-07. The explorer still shows the data because it uses https://github.com/iotaledger/inx-chronicle in the background, which doesn't prune the data

**Comment by abcen7** [comment]
Thanks for feedback, finally we created mqtt-worker for outsource IOTA transactions! <3
