### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#340]
- [ ] `sdk/tests/wallet/claim_outputs.rs` often fails

**Comment by Thoralf-M** [comment]
Went through a few runs and also saw
claim_2_native_tokens_no_outputs_in_claim_account
test_get_utxo_changes_by_id
mint_and_burn_native_tokens
mint_and_burn_nft_with_alias
send_nft

**Comment by Thoralf-M** [comment]
I have run the tests locally with a private tangle many times and they always pass, so I think the tests itself are fine, but there is an issue with the private tangle in the CI, maybe the indexer doesn't get updated fast enough with new outputs which then makes some tests fail since we expect to get them after a transaction got confirmed
