### ISSUE TITLE
[Bug]: Deadlock when sending transactions in parallel

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#406]
### Issue description

^

### Version

develop

### Expected behaviour

If sending transactions in parallel with one wallet account isn't supposed to be possible, then it should just process one transaction after the other, but it should make progress.

### Actual behaviour

Calling `wallet.send_amount` or `wallet.send` concurrently (or in parallel) consistently deadlocks.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Run the `multithread (former ping)` sdk wallet example from the #373 PR on a linux machine.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by Thoralf-M** [comment]
Seems to be related to the event_emitter (probably in combination with the account or storage lock), because without the event feature it works
Also replacing the Mutex with a RwLock seems to solve the issue https://github.com/Thoralf-M/iota-sdk/commit/cde2f731d0d7b084cf753c8d03735a35d04b0953, but have only tested with this example

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/iota-sdk/pull/417 most probably made it work again already, https://github.com/iotaledger/iota-sdk/pull/459 should further prevent it from happening again
