### ISSUE TITLE
[Bug]: Ethereum app locked status returns wrong value when connected to the sdk.

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/iota-sdk#491]
### Issue description

Firefly tries to get the ledger status from the Ethereum Ledger app through `getLedgerNanoStatus` on the AccountManager object. The issue is that even if the app is locked, we get a `locked: false` property returned by the sdk. Could you guys look into this?

### Version

rc.35

### Expected behaviour

Whenever the Ethereum app is locked, we should get a `locked: true` response

### Actual behaviour

Locked Ethereum app returns a `locked: false` state
![image](https://github.com/iotaledger/iota-sdk/assets/45079109/4d78144e-72b9-4deb-a9e7-d948bebb6335)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Steps to reproduce
1. Opt.: Set your ledger timeout to 1 min
2. Open the Ethereum app on Ledger
3. Wait until the ledger locks
4. The following status is returned from the sdk:

### Errors

None

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

**Comment by shufps** [comment]
The problem is following:

The App-Name is returned by an API call to the Bolos OS. This works with every app.

But the locked status is part of a IOTA/Shimmer specific API call the Ethereum App can't know.

The correct behaviour would not to return `true` or `false` in case the Ethereum App is opened but more some kind of `I don't know` - could be `None` in rust or `null` in Javascript.

Probably default values should be `Option<bool>` here:

https://github.com/iotaledger/iota-sdk/blob/develop/sdk/src/client/secret/ledger_nano.rs#L419
